# Generated by Django 5.0.3 on 2024-03-25 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=1800)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('picture_url', models.URLField(blank=True, null=True)),
                ('is_hidden', models.BooleanField(blank=True, null=True)),
                ('number_of_endorsements', models.IntegerField(blank=True, null=True)),
                ('email_url', models.EmailField(blank=True, max_length=254, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('portfolio_url', models.URLField(blank=True, null=True)),
                ('contact_preference', models.CharField(choices=[('Contact Form', 'Contact Form'), ('Email', 'Email'), ('LinkedIn', 'LinkedIn'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram')], default='Email', max_length=30)),
                ('is_open_to_mentor', models.BooleanField(blank=True, null=True)),
                ('is_seeking_mentorship', models.BooleanField(blank=True, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
