# Generated by Django 5.0.3 on 2024-03-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('bio', models.CharField(max_length=1800)),
                ('location', models.JSONField()),
                ('picture_url', models.URLField()),
                ('is_hidden', models.BooleanField()),
                ('number_of_endorsements', models.IntegerField()),
                ('email_url', models.EmailField(max_length=254)),
                ('facebook_url', models.URLField()),
                ('instagram_url', models.URLField()),
                ('github_url', models.URLField()),
                ('linked_in_url', models.URLField()),
                ('portfolio_url', models.URLField()),
                ('is_open_to_mentor', models.BooleanField()),
                ('is_seeking_mentorship', models.BooleanField()),
                ('date_created', models.DateTimeField()),
            ],
        ),
    ]
