# Generated by Django 5.0.3 on 2024-03-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_profiles_profile_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['industry_name'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='industries',
            field=models.ManyToManyField(related_name='profiles', to='profiles.industry'),
        ),
    ]
