# Generated by Django 5.0.3 on 2024-03-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_tags_alter_profile_industries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_type', models.CharField(choices=[('Volunteering', 'Volunteering'), ('Project', 'Project'), ('Talk', 'Talk'), ('Mentoring', 'Mentoring'), ('Job', 'Job')], default='Job', max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('url', models.URLField(blank=True, null=True)),
                ('picture_url', models.URLField(blank=True, null=True)),
                ('is_present_experience', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Experiences',
            },
        ),
    ]
