# Generated by Django 5.0.3 on 2024-03-31 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile_experiences', to='profiles.profile'),
            preserve_default=False,
        ),
    ]
